name: Release
on:
  push:
    tags:
      - '**'
jobs:
  install-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Install Cpdetector
        run: mvn install:install-file -Dfile=${{ github.workspace }}/lib/cpdetector-1.0.10.jar -DgroupId=info.monitorenter.cpdetector -DartifactId=cpdetector -Dversion=1.0.10 -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true
      - name: Install chardet
        run: mvn install:install-file -Dfile=${{ github.workspace }}/lib/chardet-1.0.jar -DgroupId=org.mozilla.intl -DartifactId=chardet -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true
      - name: Install Dependency
        run: mvn clean install -Dmaven.test.skip=true
      - name: Release package
        run: mvn --batch-mode deploy -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
